[project]
name = "baemillion-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certifi==2024.12.14",
    "charset-normalizer==3.4.1",
    "idna==3.10",
    "pillow==11.0.0",
    "requests==2.32.3",
    "urllib3==2.3.0",
]
